<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>OrbitAOS.V6.Domain</RootNamespace>
    <AssemblyName>OrbitAOS.V6.Domain</AssemblyName>
  </PropertyGroup>

</Project>
