<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>OrbitAOS.Application</RootNamespace>
    <AssemblyName>OrbitAOS.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrbitAOS.Domain\OrbitAOS.Domain.csproj" />
  </ItemGroup>

</Project>
